### ISSUE TITLE
Does this support shell pages?

### ISSUE THREAD

**Issue by NogginBox** [matt-goldman/Maui.Plugins.PageResolver#2]
I'm trying to use this with Shell and it doesn't seem to work. I may be using Shell wrong as it's my first time. This is the code I have for my shell page.

```
<?xml version="1.0" encoding="utf-8" ?>
<Shell xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:pages="clr-namespace:Garsonix.LinkCheckerApp.Pages"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    x:Class="Garsonix.LinkCheckerApp.MainPage">

    <FlyoutItem FlyoutDisplayOptions="AsMultipleItems">
        <Tab Title="Report">
            <ShellContent ContentTemplate="{DataTemplate pages:ResourcesListPage}" />
        </Tab>
    </FlyoutItem>
</Shell>
```

My ```ResourcesListPage``` has one constructor injected dependency and the page and its dependency are both registered with DI.

So does PageResolver support shell and I'm doing it wrong, or does it not and I should be doing this a different way?

If it does support it, could you add an example to the instructions. If it doesn't, would it be possible for it to do so?

**Comment by matt-goldman** [comment]
It's not really meant for use with Shell, given that the intended use is for scenarios where you would otherwise `new` a page. E.g., to replace
```csharp
var myPage = new MyPage();
await Navigation.PushAsync(myPage);
```
Given that you don't use this pattern in Shell, I'm not sure how you would use it.

Also, I'm not sure yet as I'm waiting for the team to explain how it will work, but I'm pretty sure the GA version of .NET MAUI will do this for you with Shell. I.e., register your dependencies and then using Shell routes just navigate to your page and it will resolve them for you.

Anyway in the meantime happy to help if I can.

Can you let me know how you're using it in your code?

**Comment by matt-goldman** [comment]
Thinking about it, one way you could go would be to use the service locator pattern and call the resolver in your constructor, rather than injecting the dependencies.

E.g., instead of:
```csharp
public class ResourcesListPage : ContentPage
{
    public ResourcesListPage(ResourcesListViewModel viewModel)
    {
        BindingContext = viewModel;
    }
}
```
you could use
```csharp
public class ResourcesListPage : ContentPage
{
    public ResourcesListPage()
    {
        var viewModel = Resolver.Resolve<ResourcesListViewModel>();
        BindingContext = viewModel;
    }
}
```

This might get you through for now, but I think this is an anti-pattern, and once we get some clarification from the MAUI team about how to use DI with Shell you would probably want to update it.

**Comment by NogginBox** [comment]
Thanks for the advice. Looks like the anti pattern is a good way to go for now, even if it makes me a little sad. I should be able to use a dependency injected constructor for testing alongside the parameter free constructor.

There is this PR for MAUI at the moment that looks promising to fix this in the hopefully near future:
https://github.com/dotnet/maui/pull/3375

**Comment by bakerhillpins** [comment]
@NogginBox  Just in case folks find this and avoid trying... I've taken the sample and added Shell at the root and it works as is since it makes use of `INavigation.PushAsync` not `Shell.Current.GoToAsync`.  There is a weird display artifact when you navigate back to the ShellContent page when the navigation bar is removed. 

Interestingly `ActivatorUtilities.CreateInstance` actually calls the `IQueryAttributable` interface but since the attached property is not public the dictionary is always empty. Though it doesn't really matter since you already have the Page/VM objects after the create call returns so you could pass in whatever you want.  

As an aside It might make sense to add a way to push Navigation Parameters to the extension methods which then test for the `IQueryAttributable` interface.

**Comment by matt-goldman** [comment]
Thanks @bakerhillpins. Shell has built in dependency resolution, so I wouldn't use PageResolver for pages that have routes registered in Shell. It's only real use in a Shell app would be for modal pages, or potentially for the Autoreg add-on.

> As an aside It might make sense to add a way to push Navigation Parameters to the extension methods which then test for the IQueryAttributable interface.

That's in interesting idea, I'll look into that!
